create table if not exists employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
    name varchar(55) not null,
    date_of_birth date not null,
    gender enum('MALE', 'FEMALE','OTHER'),
    image varchar(255),
    note varchar(255),
    created_date datetime default now(),
    updated_date datetime default now()
    );